### ISSUE TITLE
neo4j database connect successfully but the callback isn't work

### ISSUE THREAD

**Issue by mis101bird** [VeliovGroup/ostrio-Neo4jreactivity#71]
Hi, 
I connect the neo4j database as following code. The code is on server side.
![2016-11-02 5 49 25](https://cloud.githubusercontent.com/assets/8818527/19924061/49211d9c-a125-11e6-9fc0-52c9206b70af.png)
Although the database connect successfully, the callback didn't have any response.
![2016-11-02 5 50 34](https://cloud.githubusercontent.com/assets/8818527/19924102/77e45e46-a125-11e6-8ce9-79731aae1e2e.png)
Does any step I miss?
Thank you.

**Comment by dr-dimitru** [comment]
Hi @mis101bird 
1. Currently I recommend to use more stable (_but server only_) [neo4jDriver](https://github.com/VeliovGroup/ostrio-neo4jdriver) (based on [neo4j-fiber](https://github.com/VeliovGroup/neo4j-fiber))

Okay, back to your question - As this code asynchronous connection with DB established after `query`. That's why you have connection error first, and then message about successful connection. You may wrap `query` into `Meteor.setTimeout`. Unfortunately there is no connection callback

**Comment by mis101bird** [comment]
Thank you. It works! And thanks for the recommendation.
